// Code generated by protoc-gen-go. DO NOT EDIT.
// source: postpb/post.proto

package postpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_254f6e2bf6959fa1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Post) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UserPosts struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPosts) Reset()         { *m = UserPosts{} }
func (m *UserPosts) String() string { return proto.CompactTextString(m) }
func (*UserPosts) ProtoMessage()    {}
func (*UserPosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_254f6e2bf6959fa1, []int{1}
}

func (m *UserPosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPosts.Unmarshal(m, b)
}
func (m *UserPosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPosts.Marshal(b, m, deterministic)
}
func (m *UserPosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPosts.Merge(m, src)
}
func (m *UserPosts) XXX_Size() int {
	return xxx_messageInfo_UserPosts.Size(m)
}
func (m *UserPosts) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPosts.DiscardUnknown(m)
}

var xxx_messageInfo_UserPosts proto.InternalMessageInfo

func (m *UserPosts) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type PostText struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostText) Reset()         { *m = PostText{} }
func (m *PostText) String() string { return proto.CompactTextString(m) }
func (*PostText) ProtoMessage()    {}
func (*PostText) Descriptor() ([]byte, []int) {
	return fileDescriptor_254f6e2bf6959fa1, []int{2}
}

func (m *PostText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostText.Unmarshal(m, b)
}
func (m *PostText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostText.Marshal(b, m, deterministic)
}
func (m *PostText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostText.Merge(m, src)
}
func (m *PostText) XXX_Size() int {
	return xxx_messageInfo_PostText.Size(m)
}
func (m *PostText) XXX_DiscardUnknown() {
	xxx_messageInfo_PostText.DiscardUnknown(m)
}

var xxx_messageInfo_PostText proto.InternalMessageInfo

func (m *PostText) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PostText) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "postpb.Post")
	proto.RegisterType((*UserPosts)(nil), "postpb.UserPosts")
	proto.RegisterType((*PostText)(nil), "postpb.PostText")
}

func init() { proto.RegisterFile("postpb/post.proto", fileDescriptor_254f6e2bf6959fa1) }

var fileDescriptor_254f6e2bf6959fa1 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc8, 0x2f, 0x2e,
	0x29, 0x48, 0xd2, 0x07, 0x51, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x21, 0x25,
	0x27, 0x2e, 0x96, 0x80, 0xfc, 0xe2, 0x12, 0x21, 0x3e, 0x2e, 0x26, 0xcf, 0x14, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xd6, 0x20, 0x26, 0xcf, 0x14, 0x21, 0x31, 0x2e, 0xb6, 0xd0, 0xe2, 0xd4, 0x22, 0xcf,
	0x14, 0x09, 0x26, 0xb0, 0x18, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x12, 0x92, 0x5a, 0x51, 0x22, 0xc1,
	0xac, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x2b, 0xe9, 0x73, 0x71, 0x82, 0x64, 0x41, 0xe6, 0x14,
	0x0b, 0x29, 0x71, 0xb1, 0x82, 0x19, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x3c, 0x7a, 0x10,
	0x8b, 0xf4, 0x40, 0x82, 0x41, 0x10, 0x29, 0x25, 0x33, 0x2e, 0x0e, 0x10, 0x03, 0xa4, 0x19, 0xc9,
	0x22, 0x46, 0xac, 0x16, 0x31, 0x21, 0x2c, 0x32, 0xb2, 0xe2, 0xe2, 0x06, 0xe9, 0x0b, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2, 0xe6, 0x62, 0x77, 0x4c, 0x49, 0x01, 0x3b, 0x5f, 0x00, 0xd9,
	0x1a, 0x90, 0x5a, 0x29, 0x14, 0x8b, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xfe, 0x36, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xb7, 0x1c, 0x9a, 0x7a, 0x0c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	AddPost(ctx context.Context, in *PostText, opts ...grpc.CallOption) (*Post, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) AddPost(ctx context.Context, in *PostText, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/postpb.PostService/AddPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	AddPost(context.Context, *PostText) (*Post, error)
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostText)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/AddPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).AddPost(ctx, req.(*PostText))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postpb.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPost",
			Handler:    _PostService_AddPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "postpb/post.proto",
}
