// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userpb/user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	Follows              []int32  `protobuf:"varint,6,rep,packed,name=Follows,proto3" json:"Follows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetFollows() []int32 {
	if m != nil {
		return m.Follows
	}
	return nil
}

type UserListFields struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	UserType             string   `protobuf:"bytes,4,opt,name=UserType,proto3" json:"UserType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListFields) Reset()         { *m = UserListFields{} }
func (m *UserListFields) String() string { return proto.CompactTextString(m) }
func (*UserListFields) ProtoMessage()    {}
func (*UserListFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{1}
}

func (m *UserListFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListFields.Unmarshal(m, b)
}
func (m *UserListFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListFields.Marshal(b, m, deterministic)
}
func (m *UserListFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListFields.Merge(m, src)
}
func (m *UserListFields) XXX_Size() int {
	return xxx_messageInfo_UserListFields.Size(m)
}
func (m *UserListFields) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListFields.DiscardUnknown(m)
}

var xxx_messageInfo_UserListFields proto.InternalMessageInfo

func (m *UserListFields) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserListFields) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserListFields) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserListFields) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

type UserList struct {
	List                 []*UserListFields `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{2}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetList() []*UserListFields {
	if m != nil {
		return m.List
	}
	return nil
}

type Login struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{3}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type AddUserParameters struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserParameters) Reset()         { *m = AddUserParameters{} }
func (m *AddUserParameters) String() string { return proto.CompactTextString(m) }
func (*AddUserParameters) ProtoMessage()    {}
func (*AddUserParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{4}
}

func (m *AddUserParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserParameters.Unmarshal(m, b)
}
func (m *AddUserParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserParameters.Marshal(b, m, deterministic)
}
func (m *AddUserParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserParameters.Merge(m, src)
}
func (m *AddUserParameters) XXX_Size() int {
	return xxx_messageInfo_AddUserParameters.Size(m)
}
func (m *AddUserParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserParameters.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserParameters proto.InternalMessageInfo

func (m *AddUserParameters) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AddUserParameters) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AddUserParameters) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddUserParameters) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginDetails struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginDetails) Reset()         { *m = LoginDetails{} }
func (m *LoginDetails) String() string { return proto.CompactTextString(m) }
func (*LoginDetails) ProtoMessage()    {}
func (*LoginDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{5}
}

func (m *LoginDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginDetails.Unmarshal(m, b)
}
func (m *LoginDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginDetails.Marshal(b, m, deterministic)
}
func (m *LoginDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginDetails.Merge(m, src)
}
func (m *LoginDetails) XXX_Size() int {
	return xxx_messageInfo_LoginDetails.Size(m)
}
func (m *LoginDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginDetails.DiscardUnknown(m)
}

var xxx_messageInfo_LoginDetails proto.InternalMessageInfo

func (m *LoginDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginDetails) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{6}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FollowerParameters struct {
	UserId               int32    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FollowerId           int32    `protobuf:"varint,2,opt,name=FollowerId,proto3" json:"FollowerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowerParameters) Reset()         { *m = FollowerParameters{} }
func (m *FollowerParameters) String() string { return proto.CompactTextString(m) }
func (*FollowerParameters) ProtoMessage()    {}
func (*FollowerParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{7}
}

func (m *FollowerParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerParameters.Unmarshal(m, b)
}
func (m *FollowerParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerParameters.Marshal(b, m, deterministic)
}
func (m *FollowerParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerParameters.Merge(m, src)
}
func (m *FollowerParameters) XXX_Size() int {
	return xxx_messageInfo_FollowerParameters.Size(m)
}
func (m *FollowerParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerParameters.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerParameters proto.InternalMessageInfo

func (m *FollowerParameters) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FollowerParameters) GetFollowerId() int32 {
	if m != nil {
		return m.FollowerId
	}
	return 0
}

type Status struct {
	ResponseStatus       bool     `protobuf:"varint,1,opt,name=ResponseStatus,proto3" json:"ResponseStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{8}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetResponseStatus() bool {
	if m != nil {
		return m.ResponseStatus
	}
	return false
}

type NoArgs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoArgs) Reset()         { *m = NoArgs{} }
func (m *NoArgs) String() string { return proto.CompactTextString(m) }
func (*NoArgs) ProtoMessage()    {}
func (*NoArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{9}
}

func (m *NoArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoArgs.Unmarshal(m, b)
}
func (m *NoArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoArgs.Marshal(b, m, deterministic)
}
func (m *NoArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoArgs.Merge(m, src)
}
func (m *NoArgs) XXX_Size() int {
	return xxx_messageInfo_NoArgs.Size(m)
}
func (m *NoArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_NoArgs.DiscardUnknown(m)
}

var xxx_messageInfo_NoArgs proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "userpb.User")
	proto.RegisterType((*UserListFields)(nil), "userpb.UserListFields")
	proto.RegisterType((*UserList)(nil), "userpb.UserList")
	proto.RegisterType((*Login)(nil), "userpb.Login")
	proto.RegisterType((*AddUserParameters)(nil), "userpb.AddUserParameters")
	proto.RegisterType((*LoginDetails)(nil), "userpb.LoginDetails")
	proto.RegisterType((*UserId)(nil), "userpb.UserId")
	proto.RegisterType((*FollowerParameters)(nil), "userpb.FollowerParameters")
	proto.RegisterType((*Status)(nil), "userpb.Status")
	proto.RegisterType((*NoArgs)(nil), "userpb.NoArgs")
}

func init() { proto.RegisterFile("userpb/user.proto", fileDescriptor_2eaba19047509177) }

var fileDescriptor_2eaba19047509177 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x8b, 0xd3, 0x4c,
	0x14, 0x6d, 0x92, 0x26, 0x5f, 0xf7, 0xb6, 0x5f, 0x70, 0x87, 0x52, 0x62, 0x10, 0x29, 0xf3, 0x20,
	0x45, 0xa1, 0x2e, 0x2b, 0x28, 0x88, 0x88, 0x5d, 0xb4, 0x4b, 0xa0, 0x2c, 0x4b, 0xea, 0xfe, 0x80,
	0xac, 0x33, 0x96, 0x40, 0xda, 0x94, 0xb9, 0xd3, 0x5d, 0xfa, 0xe4, 0x1f, 0xf1, 0xc1, 0x9f, 0x2a,
	0x33, 0x93, 0x69, 0x9b, 0x94, 0xfa, 0x20, 0x3e, 0x4d, 0xef, 0xbd, 0xe7, 0xdc, 0x39, 0xf7, 0xdc,
	0x69, 0xe0, 0x7c, 0x83, 0x5c, 0xac, 0xef, 0x5f, 0xab, 0x63, 0xbc, 0x16, 0xa5, 0x2c, 0x49, 0x60,
	0x52, 0xf4, 0xa7, 0x03, 0xed, 0x3b, 0xe4, 0x82, 0x84, 0xe0, 0x26, 0x2c, 0x72, 0x86, 0xce, 0xc8,
	0x4f, 0xdd, 0x84, 0x91, 0x67, 0x70, 0x36, 0xcd, 0x05, 0xca, 0x9b, 0x6c, 0xc9, 0x23, 0x77, 0xe8,
	0x8c, 0xce, 0xd2, 0x7d, 0x82, 0xc4, 0xd0, 0x99, 0x65, 0x55, 0xd1, 0xd3, 0xc5, 0x5d, 0x4c, 0xfa,
	0xe0, 0x7f, 0x59, 0x66, 0x79, 0x11, 0xb5, 0x75, 0xc1, 0x04, 0x8a, 0x71, 0x9b, 0x21, 0x3e, 0x96,
	0x82, 0x45, 0xbe, 0x61, 0xd8, 0x98, 0x44, 0xf0, 0xdf, 0xb4, 0x2c, 0x8a, 0xf2, 0x11, 0xa3, 0x60,
	0xe8, 0x8d, 0xfc, 0xd4, 0x86, 0xf4, 0x01, 0x42, 0xa5, 0x6e, 0x96, 0xa3, 0x9c, 0xe6, 0xbc, 0x60,
	0xf8, 0x0f, 0x75, 0xc6, 0xd0, 0x51, 0xbd, 0xbf, 0x6e, 0xd7, 0xbc, 0x92, 0xba, 0x8b, 0xe9, 0x5b,
	0x53, 0x53, 0xf7, 0x92, 0x97, 0xd0, 0x56, 0x67, 0xe4, 0x0c, 0xbd, 0x51, 0xf7, 0x72, 0x30, 0x36,
	0xce, 0x8d, 0xeb, 0xba, 0x52, 0x8d, 0xa1, 0xaf, 0xc0, 0x9f, 0x95, 0x8b, 0x7c, 0x45, 0x28, 0xf8,
	0x0a, 0x80, 0x15, 0xab, 0x77, 0xc8, 0x4a, 0x4d, 0x89, 0xfe, 0x80, 0xf3, 0x09, 0x63, 0xea, 0xf7,
	0x6d, 0x26, 0xb2, 0x25, 0x97, 0x5c, 0x60, 0x7d, 0x1e, 0xe7, 0x4f, 0xf3, 0xb8, 0xa7, 0x7c, 0xf7,
	0x4e, 0xf9, 0xde, 0xae, 0xfb, 0x4e, 0x3f, 0x41, 0x4f, 0xab, 0xfd, 0xcc, 0x65, 0x96, 0x17, 0xb8,
	0xef, 0xe0, 0x9c, 0xea, 0xe0, 0x36, 0x3a, 0x44, 0x10, 0x28, 0xfd, 0x09, 0x6b, 0xee, 0x85, 0xce,
	0x80, 0x98, 0x25, 0xd6, 0xa6, 0x1b, 0x58, 0x7c, 0x85, 0xb4, 0xec, 0xe7, 0x00, 0x16, 0x9d, 0x98,
	0x5b, 0xfc, 0xf4, 0x20, 0x43, 0x2f, 0x20, 0x98, 0xcb, 0x4c, 0x6e, 0x90, 0xbc, 0x80, 0x30, 0xe5,
	0xb8, 0x2e, 0x57, 0xc8, 0x4d, 0x46, 0x77, 0xea, 0xa4, 0x8d, 0x2c, 0xed, 0x40, 0x70, 0x53, 0x4e,
	0xc4, 0x02, 0x2f, 0x7f, 0x79, 0xd0, 0x55, 0xd7, 0xcc, 0xb9, 0x78, 0xc8, 0xbf, 0x71, 0x72, 0x01,
	0xde, 0x84, 0x31, 0xf2, 0xd4, 0xae, 0xe4, 0x68, 0x07, 0x71, 0x6d, 0x5b, 0xb4, 0x45, 0x3e, 0xc2,
	0xe0, 0x9a, 0x4b, 0x15, 0x5c, 0x6d, 0xb5, 0x27, 0xbb, 0x97, 0xdb, 0xb7, 0xc8, 0x43, 0x1f, 0x8f,
	0xf8, 0xef, 0xed, 0x74, 0xfa, 0x9f, 0x16, 0xdb, 0xea, 0xb1, 0x3f, 0x71, 0x68, 0x6b, 0xd5, 0x14,
	0x2d, 0xf2, 0x01, 0x7a, 0x77, 0xab, 0xef, 0x7f, 0xcf, 0x56, 0xca, 0x2d, 0x74, 0xbe, 0x59, 0x2c,
	0x38, 0xca, 0xbc, 0x5c, 0x21, 0x09, 0x0f, 0x35, 0x26, 0x2c, 0x7e, 0xd2, 0x7c, 0xd7, 0xb4, 0x45,
	0xde, 0x41, 0xbf, 0x9a, 0xdb, 0x76, 0xc0, 0xab, 0xad, 0xda, 0x75, 0x83, 0xfb, 0x7f, 0xcd, 0x05,
	0xda, 0x22, 0x63, 0xe8, 0x5e, 0x73, 0x39, 0x29, 0x0a, 0xfd, 0xd0, 0xf7, 0x78, 0xb3, 0x91, 0x23,
	0xfc, 0x7d, 0xa0, 0x3f, 0x4a, 0x6f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x87, 0xa6, 0x0c,
	0xa9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Add(ctx context.Context, in *AddUserParameters, opts ...grpc.CallOption) (*User, error)
	GetUserByEmailPassword(ctx context.Context, in *LoginDetails, opts ...grpc.CallOption) (*User, error)
	FollowUser(ctx context.Context, in *FollowerParameters, opts ...grpc.CallOption) (*Status, error)
	UnfollowUser(ctx context.Context, in *FollowerParameters, opts ...grpc.CallOption) (*Status, error)
	GetFollowerSuggestions(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserList, error)
	GetUserFollowersById(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Login, error)
	GetAllUsers(ctx context.Context, in *NoArgs, opts ...grpc.CallOption) (*Login, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Add(ctx context.Context, in *AddUserParameters, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/userpb.UserService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByEmailPassword(ctx context.Context, in *LoginDetails, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/userpb.UserService/GetUserByEmailPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FollowUser(ctx context.Context, in *FollowerParameters, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/userpb.UserService/FollowUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnfollowUser(ctx context.Context, in *FollowerParameters, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/userpb.UserService/UnfollowUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowerSuggestions(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/userpb.UserService/GetFollowerSuggestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserFollowersById(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Login, error) {
	out := new(Login)
	err := c.cc.Invoke(ctx, "/userpb.UserService/GetUserFollowersById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllUsers(ctx context.Context, in *NoArgs, opts ...grpc.CallOption) (*Login, error) {
	out := new(Login)
	err := c.cc.Invoke(ctx, "/userpb.UserService/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Add(context.Context, *AddUserParameters) (*User, error)
	GetUserByEmailPassword(context.Context, *LoginDetails) (*User, error)
	FollowUser(context.Context, *FollowerParameters) (*Status, error)
	UnfollowUser(context.Context, *FollowerParameters) (*Status, error)
	GetFollowerSuggestions(context.Context, *UserId) (*UserList, error)
	GetUserFollowersById(context.Context, *UserId) (*Login, error)
	GetAllUsers(context.Context, *NoArgs) (*Login, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Add(ctx, req.(*AddUserParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByEmailPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByEmailPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/GetUserByEmailPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByEmailPassword(ctx, req.(*LoginDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowerParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/FollowUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FollowUser(ctx, req.(*FollowerParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowerParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/UnfollowUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnfollowUser(ctx, req.(*FollowerParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowerSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowerSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/GetFollowerSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowerSuggestions(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserFollowersById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserFollowersById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/GetUserFollowersById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserFollowersById(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserService/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllUsers(ctx, req.(*NoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userpb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _UserService_Add_Handler,
		},
		{
			MethodName: "GetUserByEmailPassword",
			Handler:    _UserService_GetUserByEmailPassword_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _UserService_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _UserService_UnfollowUser_Handler,
		},
		{
			MethodName: "GetFollowerSuggestions",
			Handler:    _UserService_GetFollowerSuggestions_Handler,
		},
		{
			MethodName: "GetUserFollowersById",
			Handler:    _UserService_GetUserFollowersById_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _UserService_GetAllUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userpb/user.proto",
}
